# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20  # Specify the Node.js version you want
    image: channelpartner_server
    ports:
      - "8050:8050"
    network_mode: "host"  # Use the host's network
    deploy:
      replicas: 1
    restart: always
